if(DEFINED VCPKG_TARGET_TRIPLET)
  set(ZLIB_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/vcpkg_installed/${VCPKG_TARGET_TRIPLET}/include")
  
  if(WIN32)
    set(ZLIB_LIBRARY "${CMAKE_CURRENT_SOURCE_DIR}/vcpkg_installed/${VCPKG_TARGET_TRIPLET}/bin/libzlib1.dll")
  else()
    set(ZLIB_LIBRARY "${CMAKE_CURRENT_SOURCE_DIR}/vcpkg_installed/${VCPKG_TARGET_TRIPLET}/lib/libz.so")
  endif()
else()
  if(WIN32)
    if(CMAKE_SIZEOF_VOID_P EQUAL 8)
      set(ZLIB_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/vcpkg_installed/x64-mingw-dynamic/include")
      set(ZLIB_LIBRARY "${CMAKE_CURRENT_SOURCE_DIR}/vcpkg_installed/x64-mingw-dynamic/bin/libzlib1.dll")
    else()
      set(ZLIB_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/vcpkg_installed/x86-mingw-dynamic/include")
      set(ZLIB_LIBRARY "${CMAKE_CURRENT_SOURCE_DIR}/vcpkg_installed/x86-mingw-dynamic/bin/libzlib1.dll")
    endif()
  else()
    set(ZLIB_INCLUDE_DIR "/usr/include")
    set(ZLIB_LIBRARY "/usr/lib/libz.so")
  endif()
endif()