name: Trigger vcpkg-port Update

on:
  release:
    types: [published, prereleased]

jobs:
  trigger-update:
    runs-on: ubuntu-latest
    steps:
      - name: Create trigger file
        run: echo "Triggered by new release" > trigger.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: trigger
          path: trigger.txt
