name: Trigger vcpkg-port Update

on:
  release:
    types: [published, prereleased]

jobs:
  trigger-update:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository dispatch event
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: token ${{ secrets.REPO_DISPATCH_TOKEN }}" \
               https://api.github.com/repos/filesverse/vcpkg-port/dispatches \
               -d '{"event_type": "update-portfile"}'
